#!/usr/bin/env zsh

NOTES_DIR="$HOME/notes"

pushd "$NOTES_DIR"
trap 'popd' 1 3 15 

cmd=($EDITOR -c 'Goyo' $@)
files=($($(which vifm) --delimiter ' ' --choose-files -))

if (( ${#files} > 0 )); then
  exec ${cmd[*]} -- "${files[@]}"
else
  exec ${cmd[*]}
fi

