#!/usr/bin/env zsh

function cyclethemes() {
  local i=1
  while true; do
    local name="${@[$i]}"
    local cmd="base16_${name}"
    echo "[${i}/${#@}] $name"
    eval $cmd
    local vim_pane_id=$(tmux list-panes -F '#{pane_id}:#{pane_current_command}' | rg 'vim' | cut -d: -f1)
    [ -n $vim_pane_id ] && tmux send-keys -t ".$vim_pane_id" "escape" "escape" ":source \$MYVIMRC" "enter"
    read -s -k 1
    if [ $i -lt $#@ ]; then
      i=$((i + 1))
    else
      i=1
    fi
  done
}

function cycle_light() {
  local favorites=(
    atelier-forest-light
    atelier-heath-light
    atelier-lakeside-light
    atelier-seaside-light
    equilibrium-gray-light
    equilibrium-light
    gruvbox-light-medium
    gruvbox-light-soft
    huminoid-light
    unikitty-light
  )
  cyclethemes $favorites
}

function cycle_dark() {
  local favorites=(
    3024
    ashes
    atelier-estuary
    atelier-savanna
    atlas
    circus
    decaf
    espresso
    flat
    gruvbox-dark-medium
    gruvbox-dark-pale
    gruvbox-dark-soft
    helios
    material
    mocha
    monokai
    nord
    nova
    oceanicnext
    outrun-dark
    phd
    porple
    sandcastle
    spacemacs
    unikitty-dark
  )
  cyclethemes $favorites
}

function testcolor() {
  awk 'BEGIN{
      s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
      for (colnum = 0; colnum<77; colnum++) {
          r = 255-(colnum*255/76);
          g = (colnum*510/76);
          b = (colnum*255/76);
          if (g>255) g = 510-g;
          printf "\033[48;2;%d;%d;%dm", r,g,b;
          printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
          printf "%s\033[0m", substr(s,colnum+1,1);
      }
      printf "\n";
  }'
}

function colortest() {
  local T='gYw'   # The test text

  echo -e "\n                 40m     41m     42m     43m\
       44m     45m     46m     47m";

  for FGs in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
             '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
             '  36m' '1;36m' '  37m' '1;37m';
    do FG=${FGs// /}
    echo -en " $FGs \033[$FG  $T  "
    for BG in 40m 41m 42m 43m 44m 45m 46m 47m;
      do echo -en "$EINS \033[$FG\033[$BG  $T  \033[0m";
    done
    echo;
  done
  echo
}

function colortest256() {
  for i in {0..255} ; do
      printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
      if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
          printf "\n";
      fi
  done
}

alias theme=cyclethemes
