#!/usr/bin/env bash

# fzfhistory - repeat history
fzfhistory() {
  eval $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac --header="[[history-grep]]" | sed -r 's/ *[0-9]*\*? *//' | sed -r 's/\\/\\\\/g')
}

alias h=fzfhistory

