#!/usr/bin/env zsh

# Build or attach a tmux session for project Convoy Connect.

declare -A LAYOUT_FUNCS=([default]=layout_default [basic]=layout_basic [ide1]=layout_ide1 [ide2]=layout_ide2)

function layout_default() {
}

function layout_basic() {
  [[ -z "$TMUX" ]] && { echo "Not running in tmux" >&2 ; return 1 ; }
  [[ -n "$1" ]] && local -r WINDOW="$1" || local -r WINDOW="$(tmux display-message -p -F '#{window_id}')"
  tmux send-keys -t "$WINDOW" "$EDITOR" "Enter"
}

# ide1
function layout_ide1() {
  [[ -z "$TMUX" ]] && { echo "Not running in tmux" >&2 ; return 1 ; }
  [[ -n "$1" ]] && local -r WINDOW="$1" || local -r WINDOW="$(tmux display-message -p -F '#{window_id}')"
  [[ -n "$2" ]] && local -r CWD="$2" || local -r CWD="$(pwd)"
  tmux split-window -d -t "$WINDOW.1" -h -c "$CWD"
  tmux split-window -d -t "$WINDOW.2" -v -c "$CWD"
  tmux split-window -d -t "$WINDOW.3" -v -c "$CWD"
  tmux select-layout -t "$WINDOW.1" main-vertical \; run-shell -t "$WINDOW.1" '~/.scripts/tx-update-main-pane-dims.sh -w 50 -h 65'
  tmux send-keys -t "$WINDOW.1" "$EDITOR" "Enter"
  tmux select-pane -t "$WINDOW.1"
}

# $1 - project name or absolute path to repo dir
# $2 - layout name
function make_project() {
  local SESSION
  local LAYOUT
  local BG=0
  [[ -n "$1" ]] && SESSION="$1"
  [[ -n "$2" ]] && LAYOUT="$2" || LAYOUT='basic'
  [ "$3" = "bg" ] && BG=1

  tmux start-server &>/dev/null

  local CHANGE_COMMAND
  if [[ -n "$TMUX" ]]; then CHANGE_COMMAND='switch-client'; else CHANGE_COMMAND='attach-session'; fi

  #
  # Switch to existing session.
  #
  
  if [[ -n "$SESSION" ]]; then
    tmux has-session -t "$SESSION" &> /dev/null
    if [ "$?" = "0" ]; then
      # Attach to existing session.
      if [ ! $BG -eq 1 ]; then
        echo "Attaching to existing session..."; sleep 0.5
        tmux $CHANGE_COMMAND -t "$SESSION"
      else
        echo "$SESSION: already started"
      fi
      return 0
    fi
  fi

  #
  # Build new session.
  #

  echo "$SESSION"
  echo "$LAYOUT"
  echo "$BG"

  local ROOT
  local REPOS
  case "$SESSION" in
    shipotle)
      ROOT="$HOME/code/convoyinc"
      REPOS=(shipotle-api)
      ;;
    nacho)
      ROOT="$HOME/code/convoyinc"
      REPOS=(nacho-dashboard)
      ;;
    sss)
      ROOT="$HOME/code/convoyinc"
      REPOS=(shipment-search-service)
      ;;
    gss)
      ROOT="$HOME/code/convoyinc"
      REPOS=(global-search-service)
      ;;
    pricing)
      ROOT="$HOME/code/convoyinc"
      REPOS=(pricing-service)
      ;;
    dotfiles)
      ROOT="$HOME/code/camflint"
      REPOS=(dotfiles)
      ;;
    caflint-scripts)
      ROOT="$HOME/code/convoyinc"
      REPOS=(caflint-scripts)
      ;;
    notes)
      ROOT="$HOME"
      REPOS=(notes)
      ;;
    scratch)
      ROOT="$HOME"
      REPOS=(scratch)
      ;;
    *)
      if [ -z "$SESSION" ]; then
        ROOT="$(dirname $(pwd))"
        SESSION="$(basename $(pwd))"
        REPOS=("$SESSION")
      else
        ROOT="$(dirname $SESSION)"
        SESSION="$(basename $SESSION)"
        REPOS=("$SESSION")
      fi
      ;;
  esac

  if [ ! -d "$ROOT" ]; then
    echo "ERROR: invalid root: $ROOT" >&2
    return 1
  fi

  local x
  local y
  if [[ -n "$TMUX" ]]; then
    x=$(tmux display-message -p -F '#{client_width}')
    y=$(tmux display-message -p -F '#{client_height}')
  else
    x=$(tput cols)
    y=$(tput lines)
  fi

  tmux new-session -c "$ROOT" -n main -s "$SESSION" -d -x $x -y $y &>/dev/null

  local REPO_WIN
  local REPO_ROOT
  for name in "${REPOS[@]}"; do
    REPO_WIN="$SESSION:$name"
    REPO_ROOT="$ROOT/$name"
    if [ ! -d "$REPO_ROOT" ]; then
      echo "ERROR: invalid repo root: $REPO_ROOT" >&2
      return 1
    fi
    tmux new-window -d -t "$SESSION" -c "$REPO_ROOT" -n "$name"
    ${LAYOUT_FUNCS[$LAYOUT]} "$REPO_WIN" "$REPO_ROOT"
  done
  tmux kill-window -t "$SESSION:main" &>/dev/null
  tmux select-window -t "$SESSION:1" &>/dev/null

  if [ ! $BG -eq 1 ]; then
    tmux $CHANGE_COMMAND -t "$SESSION"
  else 
    echo "$SESSION: started"
  fi
}

function up() {
  # Start most frequently-used projects first, to control the session ID sequence.
  # This makes switching between them easier.
  make_project shipotle basic bg
  make_project nacho basic bg
  make_project dotfiles basic bg
  make_project caflint-scripts basic bg
  make_project notes basic bg
  make_project scratch basic bg

  # Now open a project for every repo.
  for path in (fd --type d --max-depth 1 --absolute-path -g '*' "$HOME/code/convoyinc"); do
    make_project "$path" basic bg
  done
}

alias ide=ide1
alias ide1=layout_ide1
alias ide2=layout_ide2
alias basic=layout_basic
alias proj=make_project
alias dotfiles='proj dotfiles'
alias scripts='proj scripts'
alias nacho='proj nacho'
alias pricing='proj pricing'
