#!/usr/bin/env sh

function tmux-distribute-top() {
  if [[ -z "$TMUX" ]]; then return 1; fi

  # determine target & exclusions
  while [[ $# > 0 ]]; do
    case "$1" in
      t|--target) target="$2" ; shift ;;
      e|--exclude) exclude="$2" ; shift ;;
      *) echo "Option not supported: $1" >&2; return 1 ;;
    esac
    shift
  done

  # default fallbacks
  [[ -z "$target" ]] && target="$(tmux display-message -p -F '#{session_id}:#{window_id}')"
  
  # get pane id's at top
  ids=$(tmux list-panes -t "$target" -F '#{pane_id} #{pane_at_top}' | rg ' 1$' | awk '{ print $1 }')
  [[ -n "$exclude" ]] && \
    ids=$(echo $ids | rg -v "$exclude")
  ids=($(echo $ids | tr '\n' ' '))
  
  # get total width available
  total=$(tmux display-message -t "$target" -p -F '#{client_width}')

  # calculate width per pane - even distribution
  width=$(($total / ${#ids}))
  
  # resize each of the panes
  for id in "${ids[@]}"; do
    echo "tmux resize-pane -t "$target.$id" -x $width"
  done
}

# tx-update-main-pane-dims: 
#   Recalculates 'main-pane-width' and 'main-pane-height' using preset
#   percentages of the client width and height. 
function tx-update-main-pane-dims() {
  [ -z "$TMUX" ] && { echo "ERROR: this command must be run from tmux" >&2;
  return; 1; }

  local width height
  while getopts 'w:h:' opt; do
    case "$opt" in
      w) width=$OPTARG ;;
      h) height=$OPTARG ;;
    esac
  done

  if [[ $width -le 0 ]] || [[ $width -gt 100 ]] ||\
     [[ $height -le 0 ]] || [[ $height -gt 100 ]]; then
    echo 'ERROR: width and height must be percentage values between 1 and 100' >&2;
    return 1
  fi

  local cwidth=$(tmux display-message -pF '#{client_width}')
  local cheight=$(tmux display-message -pF '#{client_height}')

  local pwidth=$(expr $cwidth \* $width \/ 100)
  local pheight=$(expr $cheight \* $height \/ 100)

  tmux set-window-option main-pane-width $pwidth
  tmux set-window-option main-pane-height $pheight
  tmux select-layout
}

# alias ts='~/.scripts/tx-switch-session.sh'
# alias tw='~/.scripts/tx-switch-window.sh'
